// user
export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const SET_VERIFY_REQUEST: "SET_VERIFY_REQUEST" = "SET_VERIFY_REQUEST";
export const SET_VERIFY_SUCCESS: "SET_VERIFY_SUCCESS" = "SET_VERIFY_SUCCESS";
export const SET_VERIFY_FAILED: "SET_VERIFY_FAILED" = "SET_VERIFY_FAILED";

export const AUTHORIZE_REQUEST: "AUTHORIZE_REQUEST" = "AUTHORIZE_REQUEST";
export const AUTHORIZE_SUCCESS: "AUTHORIZE_SUCCESS" = "AUTHORIZE_SUCCESS";
export const AUTHORIZE_FAILED: "AUTHORIZE_FAILED" = "AUTHORIZE_FAILED";

export const LOGIN_REQUEST: "LOGIN_REQUEST" = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILED: "LOGIN_FAILED" = "LOGIN_FAILED";

// export const DELETE_USER_REQUEST: "DELETE_USER_REQUEST" = "DELETE_USER_REQUEST";
// export const DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS" = "DELETE_USER_SUCCESS";
// export const DELETE_USER_FAILED: "DELETE_USER_FAILED" = "DELETE_USER_FAILED";
//
// export const UPDATE_TOKEN_REQUEST: "UPDATE_TOKEN_REQUEST" = "UPDATE_TOKEN_REQUEST";
// export const UPDATE_TOKEN_SUCCESS: "UPDATE_TOKEN_SUCCESS" = "UPDATE_TOKEN_SUCCESS";
// export const UPDATE_TOKEN_FAILED: "UPDATE_TOKEN_FAILED" = "UPDATE_TOKEN_FAILED";
